version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
      - yarn global add serverless
  build:
    commands:
      - mkdir -p target/dev
      - mkdir target/prod
      - serverless package --package target/dev --stage dev -v -r us-east-1
      - serverless package --package target/prod --stage prod -v -r us-east-1
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/**/*
    - serverless.ts
    - deploy.sh
